# Generated by Django 3.2.6 on 2021-08-22 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonds_app', '0003_bond_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bond',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
    ]
